# Generated by Django 4.1.3 on 2023-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=255)),
                ('lastName', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('landLineNumber', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=125)),
                ('profilePicture', models.ImageField(default='database/images/default.png', upload_to='database/images')),
            ],
        ),
    ]
