# Generated by Django 4.1.3 on 2023-01-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('idAddress', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('idAnnouncement', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=700)),
                ('price', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.CharField(default='', max_length=10)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('idModule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomModule', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=255)),
                ('lastName', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('landLineNumber', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=255)),
                ('profilePicture', models.CharField(default='', max_length=500)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('idPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(default='', max_length=500)),
                ('priority', models.IntegerField(default='')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.announcements')),
            ],
        ),
        migrations.AddField(
            model_name='announcements',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.modules'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.users'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message', models.CharField(default='', max_length=255)),
                ('state', models.IntegerField(default='')),
                ('reason', models.CharField(default='', max_length=255)),
                ('dataSent', models.DateTimeField(default='')),
                ('dateResponse', models.DateTimeField(default='')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.announcements')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.users')),
            ],
        ),
        migrations.CreateModel(
            name='Favoriser',
            fields=[
                ('idAnnouncement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.announcements')),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.users')),
            ],
        ),
        migrations.CreateModel(
            name='Conserner',
            fields=[
                ('idAnnouncement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.announcements')),
                ('idCategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.categories')),
            ],
        ),
    ]
