# Generated by Django 4.1.3 on 2023-01-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='dataSent',
            new_name='dateSent',
        ),
    ]
