# Generated by Django 4.1.5 on 2023-01-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_photo', to='database.announcements'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
