# Generated by Django 4.1.3 on 2023-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_photos_path_photos_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conserner',
            name='idAnnouncement',
        ),
        migrations.RemoveField(
            model_name='conserner',
            name='idCategory',
        ),
        migrations.AddField(
            model_name='announcements',
            name='category',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='location',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='module',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Conserner',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
