# Generated by Django 4.1.4 on 2023-01-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriser',
            old_name='idAnnouncement',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='favoriser',
            old_name='idUser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='database.users'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriser',
            unique_together={('user', 'announcement')},
        ),
    ]
