# Generated by Django 4.1.3 on 2023-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_datasent_messages_datesent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='path',
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default='database/images/default.png', upload_to='database/images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(default='database/images/default.png', upload_to='database/images'),
        ),
    ]
